esphome:
  name: eh-wifi-light
  name_add_mac_suffix: true
  friendly_name: WiFi & Ligth for esp32-c6-devkitc-1
  comment: "Simple WiFi firmware to control on-board RGB-led."
  platformio_options:
    board_upload.flash_size: 8MB

esp32:
  board: esp32-c6-devkitc-1
  variant: ESP32C6
  framework:
    platform_version: https://github.com/mtornblad/platform-espressif32.git#esp32-c6
    type: esp-idf
    version: 5.1.1

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-C6-Wifi-2 Fallback Hotspot"
    password: "H6lCztSqeFaj"

captive_portal:
    
web_server:
  local: true
  port: 80

light:
  - platform: esp32_rmt_led_strip
    rgb_order: RBG
    pin: GPIO8
    num_leds: 30
    rmt_channel: 0
    chipset: ws2812
    name: "Status Led"